BarypKel/Models/ErrorViewModel.cs
namespace BarypKel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BarypKel/Controllers/AccountController.cs
using System.Threading.Tasks;
using BarypKel.Data.Entities;
using BarypKel.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
 

namespace BarypKel.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<Admin> _userManager;
        private readonly SignInManager<Admin> _signInManager;

        public AccountController(UserManager<Admin> userManager, SignInManager<Admin> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        

        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var admin = await _userManager.FindByEmailAsync(model.Email);

                if(admin == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                Microsoft.AspNetCore.Identity.SignInResult result =
                            await _signInManager.PasswordSignInAsync(admin,
                                model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Неправильный логин и (или) пароль");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await _signInManager.SignOutAsync();
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BarypKel/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BarypKel.Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using BarypKel.Domain.IRepository;
using System;
using System.IO;

namespace BarypKel.Controllers
{
    public class EventsController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EventsController(IEventRepository eventRepository, IWebHostEnvironment webHostEnvironment)
        {
            _eventRepository = eventRepository;
            _webHostEnvironment = webHostEnvironment;
        }

       
        public async Task<IActionResult> Index()
        {
            return View(await _eventRepository.ListAllAsync());
        }

        
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var @event = await _eventRepository.GetByIdAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventName,Description,Guests,EventDate")] Event @event, IFormFile eventImage)
        {
            if (ModelState.IsValid)
            {
                if (eventImage != null)
                {
                    string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Event_images");
                    var filename = UploadImage(eventImage, folderPath);

                    @event.ImageName = filename;
                }
                await _eventRepository.AddAsync(@event);
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var @event = await _eventRepository.GetByIdAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventName,Desctiption,Guests,EventDate")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                 await   _eventRepository.UpdateAsync(@event);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var @event = await _eventRepository.GetByIdAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _eventRepository.GetByIdAsync(id);
            _eventRepository.Delete(@event);
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            var @event =   _eventRepository.GetById(id);
            return @event != null;
        }

        private  string UploadImage(IFormFile image, string folderpath)
        {
            string fileName = $"{Guid.NewGuid().ToString()}_{image.FileName}";
            string filePath = Path.Combine(folderpath, fileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                image.CopyTo(stream);
            }
            return fileName;
        }
    }
}

BarypKel/Controllers/HomeController.cs
using BarypKel.Domain.IRepository;
using BarypKel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace BarypKel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEventRepository _eventRepository;

        public HomeController(ILogger<HomeController> logger, IEventRepository eventRepository)
        {
            _logger = logger;
            _eventRepository = eventRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _eventRepository.ListAllAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BarypKel/Views/Events/Create.cshtml
@model BarypKel.Data.Entities.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Guests" class="control-label"></label>
                <input asp-for="Guests" class="form-control" />
                <span asp-validation-for="Guests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p class="imageName">Изображение</p>
                <label name="imageDb" class="file">
                    <input type="file" name="eventImage" id="file" aria-label="File browser example" autofocus>
                    <span name="imageDb" class="file-custom"></span>
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BarypKel/Views/Events/Delete.cshtml
@model BarypKel.Data.Entities.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guests)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guests)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BarypKel/Views/Events/Details.cshtml
@model BarypKel.Data.Entities.Event

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guests)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guests)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BarypKel/Views/Events/Edit.cshtml
@model BarypKel.Data.Entities.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Guests" class="control-label"></label>
                <input asp-for="Guests" class="form-control" />
                <span asp-validation-for="Guests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BarypKel/Views/Events/Index.cshtml
@model IEnumerable<BarypKel.Data.Entities.Event>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guests)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guests)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BarypKel/Views/Home/Index.cshtml
@model IEnumerable<BarypKel.Data.Entities.Event>
@{
    ViewData["Title"] = "Home Page";
}


<div class="container">
    <h1 class="heading">Ближайшие события </h1>
    <div class="gallery">
        @foreach (var item in Model)
        {
            <div class="gallery-item">
            <img class="gallery-image" src="~/images/Event_Images/@item.ImageName">
            <button class="btn">Подробнее</button>
          </div>
        }
    </div>

    @*<div class="gallery">

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=500&h=500&fit=crop" alt="person writing in a notebook beside by an iPad, laptop, printed photos, spectacles, and a cup of coffee on a saucer">
                <button class="btn">Button</button>
            </div>

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=500&h=500&fit=crop" alt="sunset behind San Francisco city skyline">

            </div>

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1506045412240-22980140a405?w=500&h=500&fit=crop" alt="people holding umbrellas on a busy street at night lit by street lights and illuminated signs in Tokyo, Japan">

            </div>

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1514041181368-bca62cceffcd?w=500&h=500&fit=crop" alt="car interior from central back seat position showing driver and blurred view through windscreen of a busy road at night">

            </div>

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1445810694374-0a94739e4a03?w=500&h=500&fit=crop" alt="back view of woman wearing a backpack and beanie waiting to cross the road on a busy street at night in New York City, USA">

            </div>

            <div class="gallery-item">

                <img class="gallery-image" src="https://images.unsplash.com/photo-1486334803289-1623f249dd1e?w=500&h=500&fit=crop" alt="man wearing a black jacket, white shirt, blue jeans, and brown boots, playing a white electric guitar while sitting on an amp">

            </div>

        </div>*@

</div>

BarypKel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarypKel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/css/menu.css">
</head>
<body>
    <header class="mb-5">
        <div id="cssmenu">
            <ul>
                <li class="active"><a href="index.html"><span>zMountain</span></a></li>
                <li class="has-sub">
                    <a href="#"><span>Category</span></a>
                    <ul>
                        <li class="has-sub">
                            <a href="#"><span>Item 1</span></a>
                            <ul>
                                <li><a href="#"><span>Sub Item</span></a></li>
                                <li class="last"><a href="#"><span>Sub Item</span></a></li>
                            </ul>
                        </li>
                        <li class="has-sub">
                            <a href="#"><span>Item 2</span></a>
                            <ul>
                                <li><a href="#"><span>Sub Item</span></a></li>
                                <li class="last"><a href="#"><span>Sub Item</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Events" asp-action="Create"><span>Событие</span></a></li>
                }
                <li><a href="single.html"><span>About</span></a></li>
                <li class="last"><a href="contact.html"><span>Contact</span></a></li>
            </ul>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BarypKel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>